In [2]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
%cd /content/drive/MyDrive/멀티캠퍼스 5조/2.데이터

/content/drive/.shortcut-targets-by-id/1Mz49-WiynxJxHmmXYuWSqduV3-jd-BC7/멀티캠퍼스 5조/2.데이터

In [5]:
df = pd.read_csv('학습데이터.csv')
df.head(10)

,출발지구군,출발지상세,예정일시,승차일시,시간대(30분),요일,월,화,수,목,금,토,일,언급량,대기시간,대기시간(초),강수량,적설량,평균속도
0,은평구,구산동,2019-01-01 00:21:00,2019-01-01 02:13:11,0,1,0,1,0,0,0,0,0,48,112.0,6731.0,0.0,0.0,25.59
1,강북구,인수동,2019-01-01 00:15:00,2019-01-01 03:23:48,0,1,0,1,0,0,0,0,0,55,188.0,11328.0,0.0,0.0,24.24
2,강남구,일원1동,2019-01-01 00:49:00,2019-01-01 03:34:24,1,1,0,1,0,0,0,0,0,33,165.0,9924.0,0.0,0.0,30.75
3,성북구,보문동,2019-01-01 00:13:00,2019-01-01 03:36:11,0,1,0,1,0,0,0,0,0,61,203.0,12191.0,0.0,0.0,28.31
4,성동구,성수2가제1동,2019-01-01 01:04:00,2019-01-01 03:50:40,2,1,0,1,0,0,0,0,0,23,166.0,10000.0,0.0,0.0,31.73
5,마포구,서교동,2019-01-01 01:14:00,2019-01-01 04:00:33,2,1,0,1,0,0,0,0,0,67,166.0,9993.0,0.0,0.0,24.91
6,종로구,창신제1동,2019-01-01 00:40:00,2019-01-01 04:09:03,1,1,0,1,0,0,0,0,0,57,209.0,12543.0,0.0,0.0,25.25
7,노원구,하계1동,2019-01-01 03:32:00,2019-01-01 04:11:32,7,1,0,1,0,0,0,0,0,527,39.0,2372.0,0.0,0.0,32.34
8,영등포구,여의동,2019-01-01 00:30:00,2019-01-01 04:13:13,1,1,0,1,0,0,0,0,0,89,223.0,13393.0,0.0,0.0,29.92
9,종로구,삼청동,2019-01-01 00:02:00,2019-01-01 04:15:34,0,1,0,1,0,0,0,0,0,54,253.0,15214.0,0.0,0.0,25.25

In [6]:
car = pd.read_csv('통합데이터_운행차량수추가.csv')

In [7]:
car = car[['예정일시', '운행차량수']]

In [8]:
car = car.sort_values('예정일시')
car.head()

                       예정일시  운행차량수
455968  2019-01-01 00:02:00     11
455969  2019-01-01 00:13:00     11
455970  2019-01-01 00:15:00     11
455971  2019-01-01 00:21:00     11
455972  2019-01-01 00:30:00     11

In [10]:
car2 = car[['운행차량수']]
car2.head()

        운행차량수
455968     11
455969     11
455970     11
455971     11
455972     11

In [9]:
df = df.sort_values('예정일시')
df.head()

,출발지구군,출발지상세,예정일시,승차일시,시간대(30분),요일,월,화,수,목,금,토,일,언급량,대기시간,대기시간(초),강수량,적설량,평균속도
9,종로구,삼청동,2019-01-01 00:02:00,2019-01-01 04:15:34,0,1,0,1,0,0,0,0,0,54,253.0,15214.0,0.0,0.0,25.25
3,성북구,보문동,2019-01-01 00:13:00,2019-01-01 03:36:11,0,1,0,1,0,0,0,0,0,61,203.0,12191.0,0.0,0.0,28.31
1,강북구,인수동,2019-01-01 00:15:00,2019-01-01 03:23:48,0,1,0,1,0,0,0,0,0,55,188.0,11328.0,0.0,0.0,24.24
0,은평구,구산동,2019-01-01 00:21:00,2019-01-01 02:13:11,0,1,0,1,0,0,0,0,0,48,112.0,6731.0,0.0,0.0,25.59
8,영등포구,여의동,2019-01-01 00:30:00,2019-01-01 04:13:13,1,1,0,1,0,0,0,0,0,89,223.0,13393.0,0.0,0.0,29.92

In [12]:
df.reset_index(drop = True, inplace = True), car2.reset_index(drop = True, inplace = True)

(None, None)

In [14]:
df.head()

,출발지구군,출발지상세,예정일시,승차일시,시간대(30분),요일,월,화,수,목,금,토,일,언급량,대기시간,대기시간(초),강수량,적설량,평균속도
0,종로구,삼청동,2019-01-01 00:02:00,2019-01-01 04:15:34,0,1,0,1,0,0,0,0,0,54,253.0,15214.0,0.0,0.0,25.25
1,성북구,보문동,2019-01-01 00:13:00,2019-01-01 03:36:11,0,1,0,1,0,0,0,0,0,61,203.0,12191.0,0.0,0.0,28.31
2,강북구,인수동,2019-01-01 00:15:00,2019-01-01 03:23:48,0,1,0,1,0,0,0,0,0,55,188.0,11328.0,0.0,0.0,24.24
3,은평구,구산동,2019-01-01 00:21:00,2019-01-01 02:13:11,0,1,0,1,0,0,0,0,0,48,112.0,6731.0,0.0,0.0,25.59
4,영등포구,여의동,2019-01-01 00:30:00,2019-01-01 04:13:13,1,1,0,1,0,0,0,0,0,89,223.0,13393.0,0.0,0.0,29.92

In [15]:
df2 = pd.concat([df, car2], axis = 1)

In [16]:
df2.head()

,출발지구군,출발지상세,예정일시,승차일시,시간대(30분),요일,월,화,수,목,금,토,일,언급량,대기시간,대기시간(초),강수량,적설량,평균속도,운행차량수
0,종로구,삼청동,2019-01-01 00:02:00,2019-01-01 04:15:34,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,54.0,253.0,15214.0,0.0,0.0,25.25,11
1,성북구,보문동,2019-01-01 00:13:00,2019-01-01 03:36:11,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,61.0,203.0,12191.0,0.0,0.0,28.31,11
2,강북구,인수동,2019-01-01 00:15:00,2019-01-01 03:23:48,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,55.0,188.0,11328.0,0.0,0.0,24.24,11
3,은평구,구산동,2019-01-01 00:21:00,2019-01-01 02:13:11,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,48.0,112.0,6731.0,0.0,0.0,25.59,11
4,영등포구,여의동,2019-01-01 00:30:00,2019-01-01 04:13:13,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,89.0,223.0,13393.0,0.0,0.0,29.92,11

In [17]:
df2.columns

Index(['출발지구군', '출발지상세', '예정일시', '승차일시', '시간대(30분)', '요일', '월', '화', '수', '목',
       '금', '토', '일', '언급량', '대기시간', '대기시간(초)', '강수량', '적설량', '평균속도', '운행차량수'],
      dtype='object')

In [19]:
df2 = df2[['출발지구군', '출발지상세', '예정일시', '승차일시', '시간대(30분)', '요일', '월', '화', '수', '목',
       '금', '토', '일', '언급량', '강수량', '적설량', '평균속도', '운행차량수', '대기시간', '대기시간(초)']]

In [21]:
df2.rename(columns = {'시간대(30분)':'시간대_30분', '대기시간(초)' : '대기시간_초'}, inplace = True)
df2.head()

,출발지구군,출발지상세,예정일시,승차일시,시간대_30분,요일,월,화,수,목,금,토,일,언급량,강수량,적설량,평균속도,운행차량수,대기시간,대기시간_초
0,종로구,삼청동,2019-01-01 00:02:00,2019-01-01 04:15:34,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,54.0,0.0,0.0,25.25,11,253.0,15214.0
1,성북구,보문동,2019-01-01 00:13:00,2019-01-01 03:36:11,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,61.0,0.0,0.0,28.31,11,203.0,12191.0
2,강북구,인수동,2019-01-01 00:15:00,2019-01-01 03:23:48,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,55.0,0.0,0.0,24.24,11,188.0,11328.0
3,은평구,구산동,2019-01-01 00:21:00,2019-01-01 02:13:11,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,48.0,0.0,0.0,25.59,11,112.0,6731.0
4,영등포구,여의동,2019-01-01 00:30:00,2019-01-01 04:13:13,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,89.0,0.0,0.0,29.92,11,223.0,13393.0

In [22]:
df2.to_csv('학습데이터2.csv', index = False)